### ISSUE TITLE
Qustion about why you add code to stop composite for xfwm

### ISSUE THREAD

**Issue by CicadaSeventeen** [mviereck/dockerfile-x11docker-xfce#5]
I find xfce starts slow but mate stats much more quicker. Sometimes xfwm even fails to start. I use `startxfce4` instead and find it works better. Even without `-g` composite just fine, so I wonder why you add such code here.

**Comment by mviereck** [comment]
The code to disable compositing is only applied if the X server misses X extension composite. In that case xfwm4 has several compositing issues. This only happens with `--nxagent`.
You can reproduce the issues with:
```
x11docker --desktop --nxagent x11docker/xfce startxfce4
```
You can avoid the issue with option `--composite` that enables the extension in nxagent. This is not done by default because some other application have issues with it.

```
x11docker --desktop --nxagent --composite x11docker/xfce startxfce4
```

**Comment by CicadaSeventeen** [comment]
Thanks
